name = "Tinkering"
uuid = "3247c565-7824-4251-9eae-9a632bfbe245"
authors = ["Kyu-Young Kim <kykim@cs.stanford.edu> and contributors"]
version = "0.1.0"

[compat]
julia = "1.7.1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
